#!/usr/bin/bash

alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias g='git'
alias ginit='git init '
alias gclone='git clone '
alias gadd='git add '
alias grm='git rm '
alias gcommit='git commit '
alias gcheckout='git checkout '
alias vi='vim'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias print='echo'
alias scr='screen'
alias nau='nautilus'
alias install='sudo apt-get install'
alias remove='sudo apt-get remove'
alias gedit='leafpad'
alias freedom='ssh -N -D 7070 freedom'
alias smth='luit -encoding GBK telnet newsmth.net'
alias sob='source ~/.bashrc'
alias edb='vi ~/.bashrc'
alias lock='gnome-screensaver-command -l'
# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias cle='clear'
alias nau='nautilus'
alias x='xrdb ~/.Xresources'
alias tmux="TERM=screen-256color-bce tmux"
alias wpa='sudo wpa_supplicant -B -i wlan0 -Dwext -c ~/.wpa_supplicant.conf'
alias t='python ~/.t.py --task-dir ~/.tasks --list tasks'
alias gitc="git log --author='solos' --pretty=tformat: --numstat | gawk '{add += \$1 ; subs += \$2 ; loc += \$1 - \$2;} END {printf \"added lines: %s, removed lines: %s, total lines: %s\n\",add,subs,loc}'"
