#!/usr/bin/bash

alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias g='git'
alias ginit='git init '
alias gclone='git clone '
alias gadd='git add '
alias grm='git rm '
alias gcommit='git commit '
alias gcheckout='git checkout '
alias vi='vim'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias print='echo'
alias scr='screen'
alias nau='nautilus'
alias install='sudo apt-get install'
alias remove='sudo apt-get remove'
alias gedit='leafpad'
alias freedom='ssh -N -D 7070 freedom'
alias smth='luit -encoding GBK telnet newsmth.net'
alias sob='source ~/.bashrc'
alias edb='vi ~/.bashrc'
alias lock='gnome-screensaver-command -l'
# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias cle='clear'
alias nau='nautilus'
alias x='xrdb ~/.Xresources'
